### ISSUE TITLE
ruby-2.3.1 / rake issue

### ISSUE THREAD

**Issue by tophe** [rest-client/rest-client#540]
hello,

I have a probleme using rest-client with rake (for test integration). 
when I use the rakefile linked  with ruby-2.2.3 it work.
but when I use it with ruby-2.3.1 I have:

```
rake aborted!
NoMethodError: undefined method `this' for #<Gem::Specification:0x93ce5c mime-types-3.1>
/home/Tophe/.rvm/gems/ruby-2.3.1/gems/mime-types-3.1/lib/mime/types.rb:8:in `<top (required)>'
/home/Tophe/.rvm/gems/ruby-2.3.1/gems/rest-client-2.0.0/lib/restclient/request.rb:2:in `<top (required)>'
/home/Tophe/.rvm/gems/ruby-2.3.1/gems/rest-client-2.0.0/lib/restclient.rb:11:in `<top (required)>'
/home/Tophe/.rvm/gems/ruby-2.3.1/gems/rest-client-2.0.0/lib/rest-client.rb:2:in `<top (required)>'
/data/git/gogs.artprice.bil/artdb/artist_cli/Rakefile:1:in `<top (required)>'
/home/Tophe/.rvm/gems/ruby-2.3.1/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/home/Tophe/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
/home/Tophe/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
LoadError: cannot load such file -- rest-client
/data/git/gogs.artprice.bil/artdb/artist_cli/Rakefile:1:in `<top (required)>'
/home/Tophe/.rvm/gems/ruby-2.3.1/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/home/Tophe/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
/home/Tophe/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```

it break on the load off the rest-client

[Rakefile.txt](https://github.com/rest-client/rest-client/files/558608/Rakefile.txt)

**Comment by ab** [comment]
rest-client is tested and known to work on Ruby 2.3.1, so I think you've encountered an unrelated bug.

Have you tried upgrading rubygems? It might be related to this issue:

https://github.com/rubygems/rubygems/issues/1420

**Comment by tophe** [comment]
hello,

I was using gem v2.5.1,  after
gem update --system
Updating rubygems-update
Fetching: rubygems-update-2.6.8.gem (100%)

every thing is OK.

thank you for your help !
